server.port: 8002
#大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled: true
server.servlet.encoding.force: true
server.servlet.encoding.charset: UTF-8

#项目名称
spring.application.name: mcp-server-sse

# mcp-sever config
# mcp 服务名称
spring.ai.mcp.server.name: phuang-weather-mcp-server
# 定义mcp同步模式(必须)
spring.ai.mcp.server.type: SYNC
spring.ai.mcp.server.enabled: true
spring.ai.mcp.server.capabilities.tool: true
spring.ai.mcp.server.capabilities.resource: false
spring.ai.mcp.server.capabilities.prompt: false
spring.ai.mcp.server.capabilities.completion: false
# mcp 服务版本
spring.ai.mcp.server.version: 1.0.0
# 是否关闭stdio模式,这里采用 sse
spring.ai.mcp.server.stdio: false
# 指定用于 Web 传输的自定义 SSE 端点路径
spring.ai.mcp.server.sse-message-endpoint: /mcp/messages
spring.ai.mcp.server.see-endpoint: /sse
