<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.4</version>
        <relativePath/>
    </parent>

    <groupId>com.phuang</groupId>
    <artifactId>common-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>common-test</name>
    <description>custom-annotation-common-start 测试工程</description>

    <properties>
        <java.version>8</java.version>
        <custom-annotation-common-start.version>1.0-SNAPSHOT</custom-annotation-common-start.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.phuang</groupId>
            <artifactId>custom-annotation-common-start</artifactId>
            <version>${custom-annotation-common-start.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <!-- HLock 使用反射参数名解析 #variable。 -->
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
